edx/frontend-component-header-edx

src/SiteHeader.messages.jsx
Prepare to add i18n pipeline tools
=> fix: update duplicate message id

example/index.js, package-lock.json, package.json, src/DesktopHeader.jsx, src/Header.jsx, src/Header.messages.jsx, src/Header.test.jsx, src/MobileHeader.jsx, src/enterprise/getLearnerPortalLinks.js
BREAKING CHANGE: This package now relies upon frontend-platform instead of individual runway packages.
=> feat: upgrade to frontend-platform

src/Header.jsx
The `LOGISTRATION_MINIMAL_HEADER` environment variable removes the main menu links from the header. It also removes login/register links from the menu if the user is unauthenticated for new logistration MFE.
=> feat: add LOGISTRATION_MINIMAL_HEADER env variable

src/Header.jsx, src/MobileHeader.jsx, src/index.scss
=> fix: logistration hide user menu icon on mobile screens

src/Header.jsx
Reverts edx/frontend-component-header-edx#118
=> Revert "logistration renamed to authn"

src/DesktopHeader.jsx, src/Header.messages.jsx, src/MobileHeader.jsx, src/__snapshots__/Header.test.jsx.snap
Add skipNav link in Desktop and Mobile Headers
VAN-379
=> add skipnav link in header

package-lock.json, package.json
=> feat: upgrade platform and build

package-lock.json, package.json, src/__snapshots__/Header.test.jsx.snap
- Updated paragon to v20
- Updated snapshots
=> feat: upgraded paragon to v20 & updated snapshots

src/Header.jsx, src/Header.messages.jsx, src/learning-header/AuthenticatedUserDropdown.jsx, src/learning-header/messages.js
Adding a new link to the User Menu for logged-in users. This will redirect the user to the "Career Resource Center" or "CRC".
**GO-LIVE DATE CHANGE**
**Note that this PR should not go to Production until on or after 6 June 2023, in preparation for the launch of the CRC.**
[CAMS-1](https://2u-internal.atlassian.net/browse/CAMS-1)
=> feat: adding `Career` link to user menu

src/Notifications/NotificationSections.jsx, src/Notifications/data/__factories__/notifications.factory.js, src/Notifications/index.jsx, src/Notifications/utils.js, src/index.scss, src/learning-header/LearningHeader.jsx
[INF-962](https://2u-internal.atlassian.net/browse/INF-962)
[INF-968](https://2u-internal.atlassian.net/browse/INF-968)
[INF-965](https://2u-internal.atlassian.net/browse/INF-965)
[INF-963](https://2u-internal.atlassian.net/browse/INF-963)
[INF-969](https://2u-internal.atlassian.net/browse/INF-969)
Fixed bell icon number looks out of alignment issue
Fixed Notification timestamp is not updating issue
Fixed Dropdown notifications list shows "Earlier" instead of "Last 24 Hours" issue
Fixed notification tray height issue
Fixed Load more button is out of alignment issue
=> fix: fixed bell icon badge UI issue

src/Notifications/index.jsx
[INF-963](https://2u-internal.atlassian.net/browse/INF-963)
Fixed notification tray height issue based on footer view port height on the page
=> fix: fixed notification tray height issue based on footer height

src/Notifications/index.jsx, src/learning-header/LearningHeader.jsx
- Adjust bell icon margins
- Learning Header padding in Xl screens
**Before** 
**After**
=> fix: adjust learningHeader padding

src/learning-header/LearningHeader.jsx
[INF-1007](https://2u-internal.atlassian.net/browse/INF-1007)
fixed useLocation undefined issue of react router dom by enabling client-side routing using BrowserRouter
=> fix: fixed useLocation undefined issue of react router dom

src/learning-header/AuthenticatedUserDropdown.jsx, src/learning-header/LearningHeader.jsx
[INF-1010](https://2u-internal.atlassian.net/browse/INF-1010)
Fetched and showed the count of unseen notifications when the URL changes. For example when a user loads a new post or navigates to another tab (e.g. Topics) on the Discussion page.
=> fix: URL route issue

.env.development, .env.test, public/index.html, src/Notifications/NotificationRowItem.jsx, src/Notifications/NotificationTabs.jsx, src/Notifications/index.jsx, src/Notifications/messages.js, src/Notifications/utils.js, src/learning-header/LearningHeader.jsx
**[INF-983](https://2u-internal.atlassian.net/browse/INF-983)**
- Add a feedback icon/widget in the notification tray
- Move the feedback/icon widget behind the env variable
**Dependency** 
[edx-internal](https://github.com/edx/edx-internal/pull/8980)
=> feat: add notification feedback icon

src/index.scss
[INF-1020](https://2u-internal.atlassian.net/browse/INF-1020)
Fixed notification tray shrink issue on learning MFE
=> fix: fix notification tray shrink issue

src/Notifications/data/redux.test.js, src/Notifications/data/slice.js, src/Notifications/data/thunks.js, src/Notifications/utils.js
- Removed code based error handling for notifications API
=> fix: removed code based error handling

src/Notifications/NotificationSections.jsx, src/Notifications/data/selectors.js, src/Notifications/data/slice.js, src/Notifications/data/thunks.js, src/Notifications/messages.js, src/Notifications/notificationSections.test.jsx, src/index.scss
Added ui at the end of notification list to indicate all notifications have been viewed
=> feat: added notifications list finish ui

src/Notifications/NotificationSections.jsx, src/Notifications/NotificationTabs.jsx
[INF-1056](https://2u-internal.atlassian.net/browse/INF-1056)
There should be no tabs section in the UI when we have only one tab.
**Screenshot**
=> fix: removed discussion tab from UI

src/Header.jsx, src/Header.messages.jsx, src/Header.test.jsx, src/learning-header/AuthenticatedUserDropdown.jsx, src/learning-header/messages.js
Due to timeline changes, this reverts commit 6d8c03fca0db184ba5bda73437f2d6ee51a73bd1.
=> Revert "feat: Update Orders & Subscriptions back to Order History"

src/index.scss
[INF-1055](https://2u-internal.atlassian.net/browse/INF-1055)
**Description** 
Fixed notification tray width as per figma
**Screenshot**
=> fix: fixed width of notification tray

src/Notifications/index.jsx, src/index.scss
[INF-1053](https://2u-internal.atlassian.net/browse/INF-1053)
[INF-1058](https://2u-internal.atlassian.net/browse/INF-1058)
[INF-1059](https://2u-internal.atlassian.net/browse/INF-1059)
used Light/300 (#F2F0EF) for hover and clicked color background for bell icon
Badge is circular if there’s only one number in. 
**Screenshot**
=> fix: changed hover and clicked color of icon

src/index.scss
[INF-1059](https://2u-internal.atlassian.net/browse/INF-1059)
Fixed Badge size issue
**Screenshot**
=> fix: fixed padding issue with the badge

src/Notifications/NotificationSections.jsx, src/index.scss
[INF-1054](https://2u-internal.atlassian.net/browse/INF-1054)
Fixed issues of Colors, font weights, font colors, check mark (can be exported from Figma), check mark size, check mark color etc.
**Screenshot**
=> fix: fixed ui issues of That's all your notifications

src/index.jsx, src/index.scss, src/studio-header/BrandNav.jsx, src/studio-header/CourseLockUp.jsx, src/studio-header/HeaderBody.jsx, src/studio-header/MobileHeader.jsx, src/studio-header/MobileMenu.jsx, src/studio-header/NavDropdownMenu.jsx, src/studio-header/StudioHeader.jsx, src/studio-header/StudioHeader.test.jsx, src/studio-header/UserMenu.jsx, src/studio-header/header.scss, src/studio-header/index.js, src/studio-header/messages.js, src/studio-header/utils.js
Add new header for studio MFEs. This header will be used in the Library and Course Authoring MFEs.
=> feat: add studio header

src/Header.jsx, src/Header.messages.jsx, src/Header.test.jsx, src/learning-header/AuthenticatedUserDropdown.jsx, src/learning-header/messages.js
[REV-3693](https://2u-internal.atlassian.net/browse/REV-3693).
Previously merged this but due to timeline changes had to revert. This will not be merged until 10/02/23.
=> feat: Update Orders & Subscriptions menu item back to Order History

package-lock.json, package.json
Updated paragon version "21.3.1" in frontend-component-header-edx
=> chore: updated version for paragon

src/Notifications/NotificationSections.jsx, src/Notifications/NotificationTabs.jsx, src/Notifications/index.jsx, src/Notifications/messages.js, src/index.scss
[INF-1082](https://2u-internal.atlassian.net/browse/INF-1082)
"No notification yet" message should be visible in the notification tray when there is no notification for the user.
Figma: [Notifications](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=678-15078&mode=design)
**Screenshot**
=> feat: added no notifition yet message bar

src/Notifications/utils.js
Add icons for newly added notifications.
```
content_reported: { icon: Report, class: 'text-danger' },
response_endorsed: { icon: Verified, class: 'text-primary-500' },
response_endorsed_on_thread: { icon: Verified, class: 'text-primary-500' },
```
https://2u-internal.atlassian.net/browse/INF-1242
=> chore: added new notification icons

src/Notifications/NotificationTabs.jsx, src/Notifications/index.jsx, src/Notifications/notification.scss
[INF-1288](https://2u-internal.atlassian.net/browse/INF-1288)
Tabs bar should be locked on top.
**Before**
**After**
=> fix: fixed tabs scroll issue

src/common/style.scss
Details: https://twou.slack.com/archives/C049P0JHHJ9/p1712240297543299
https://2u-internal.atlassian.net/browse/VAN-1901
=> fix: first item could not be selected

src/DesktopHeader.jsx, src/MobileHeader.jsx, src/common/style.scss, src/index.scss, src/learning-header/AuthenticatedUserDropdown.jsx, src/learning-header/LearningHeader.test.jsx, src/studio-header/NavDropdownMenu.jsx
Fix the UserMenuItem design in the header. 
Details: https://twou.slack.com/archives/C049P0JHHJ9/p1712240297543299
=> fix: header user info menu item design

src/Notifications/notification.scss
[INF-1286](https://2u-internal.atlassian.net/browse/INF-1286)
Selected state of tabs in tray should match the figma [mockup](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=2228-11130&mode=design&t=ZYSTqx77WhBJPGBT-0).
**Before**
**After**
=> fix: fixed border issue of active nav

src/DesktopHeader.jsx, src/MobileHeader.jsx, src/__snapshots__/Header.test.jsx.snap
Description: Add facility of onClick event on header menus 
[VAN-1914](https://2u-internal.atlassian.net/browse/VAN-1914)
How it has been tested?
It has been tested locally.
This is the [PR](https://github.com/openedx/frontend-component-header/pull/494) for reference, we have done this in openedx header as well.
=> feat: add onclick facility

src/Notification/NotificationRowItem.jsx
Added notification post link class to get analytics
=> feat: added notification post link class to get analytics

src/Notification/NotificationSections.jsx, src/Notification/index.jsx, src/Notification/notification.scss
[INF-1674](https://2u-internal.atlassian.net/browse/INF-1674)
Fixed following issues
1. When clicks the tab that's already active, the contents of the tab go away
2. There seems to be some style overrides from the default Paragon tabs component, preventing focus styles from working (usability/a11y bug).
=> fix: fixed tab click issue

.env.development, .env.test, src/DesktopHeader.jsx, src/Header.jsx, src/Notification/data/hook.js, src/Notification/index.jsx, src/studio-header/MobileMenu.jsx, src/studio-header/NavDropdownMenu.jsx
[INF-1709](https://2u-internal.atlassian.net/browse/INF-1709)
- Fixed Console Errors
=> fix: console and propType errors

package-lock.json, package.json, src/Menu/menu.scss, src/index.scss, src/studio-header/StudioHeader.scss
Upon further consideration of the impact of the release plan of the `master-design-tokens` branches in `openedx` MFEs on MFE-owning teams at 2U, we will want to release the Paragon v23 upgrade for `header-edx` as a breaking change, with a new major version to ensure GoCD builds fail with mismatching peer dependencies.
=> fix: update for breaking change
