src/enterprise/getLearnerPortalLinks.js
BREAKING CHANGE: requires the presence of ENTERPRISE_LEARNER_PORTAL_HOSTNAME env var to properly generate learner portal urls
=> feat: use learner portal hostname config variable

.gitignore, package-lock.json, package.json, src/Header.jsx
Mobile:
Desktop B2C Learner:
Desktop Enterprise Learner:
URLs for both link to the Enterprise Learner Portal for that enterprise.
=> feat: ent-2683 - adds in enterprise branding to header logo

src/DesktopHeader.jsx, src/__snapshots__/Header.test.jsx.snap
Add Hotjar suppression to username on the frontend header component. This will suppress PII when we enable Hotjar Analytics for MFE that use this header.
=> VAN-41: Add hotjar suppression to PII

package-lock.json, package.json
https://openedx.atlassian.net/browse/ENT-3390
Upgraded frontend-enterprise release: https://github.com/edx/frontend-enterprise/releases/tag/v4.2.3
This fixes an issue for internal/staff users - we now only fetch your preferred enterprise and use that to make a determination about whether or not to show Order History. Previously, we fetched every enterprise the user is associated with, which for staff users, can be many.
=> fix: upgrade frontend-enterprise to 4.2.3

package-lock.json, package.json, src/DesktopHeader.jsx, src/Header.test.jsx, src/Menu/Menu.jsx, src/MobileHeader.jsx, src/__snapshots__/Header.test.jsx.snap
We updated the mobile and desktop views of the header to use the newer Avatar button design. We also bumped the version of Paragon from 7 to 12 (a breaking change).
To use the newer Avatar button design instead of building our own. The Paragon update is because the newer Avatar button design isn't available until version 12.
JIRA ticket: https://openedx.atlassian.net/browse/REV-2070
=> [REV-2070] feat: update desktop and mobile header to use avatar button

.gitignore, src/DesktopHeader.jsx, src/MobileHeader.jsx, src/__snapshots__/Header.test.jsx.snap
edX logo should be left aligned on all viewports.Currently, it is moved to center on mobile viewports which is inconsistent compared to our desktop viewports.
=> fix: align logo to left

.github/workflows/release.yml
Newer versions don't support node 12.
=> build: pin semantic-release to v16

package.json
This broke a lot of pipe line because project specify peer dependency to `paragon@^19.9.0`. At the time of this PR, the latest paragon is `20.5.0`.
=> feat: update peer dependency

src/DesktopHeader.jsx, src/__snapshots__/Header.test.jsx.snap, src/learning-header/AuthenticatedUserDropdown.jsx
Fixed the error:
```
The prop `id` is marked as required in `ForwardRef(DropdownToggle)`, but its value is `undefined`.
```
Stacktrace:
```
Warning: Failed prop type: The prop `id` is marked as required in `ForwardRef(DropdownToggle)`, but its value is `undefined`.
in ForwardRef(DropdownToggle) (created by DesktopHeader)
in DesktopHeader (created by ShimmedIntlComponent)
in ShimmedIntlComponent (created by Context.Consumer)
in injectIntl(ShimmedIntlComponent) (created by Header)
in MediaQuery (created by Header)
in Header (created by ShimmedIntlComponent)
in ShimmedIntlComponent (created by Context.Consumer)
in injectIntl(ShimmedIntlComponent)
in Router (created by AppProvider)
in Provider (created by OptionalReduxProvider)
in OptionalReduxProvider (created by AppProvider)
in …
```
=> fix:  Added id in dropdownToggle component

package-lock.json, package.json
[REV-3174](https://2u-internal.atlassian.net/browse/REV-3174).
To follow what was done in `frontend-component-header` (https://github.com/openedx/frontend-component-header/pull/275 and https://github.com/openedx/frontend-component-header/pull/282), upgrading frontend-platform to v3 and adding a range to avoid peer dependency issues with the v3 upgrade.
Note: `devDependency` required a range due to a conflict with `frontend-enterprise-utils` dependency on a v1 to v2 range for `frontend-platform`.
=> feat: Upgrade frontend-platform dependency v2 to v3 range

.github/workflows/ci.yml, .github/workflows/release.yml, package-lock.json, package.json
Ticket
[Migrate from Coveralls to Codecov ](https://github.com/openedx/frontend-wg/issues/9)
Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3
This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov
=> refactor: Moving code coverage from codecov package to CI

src/Notifications/NotificationSections.jsx, src/Notifications/utils.js
Fixed notification showing default icon
Removed icons that were not being used. Icons for new notifications will be added later when their notification type will be implemented
Ticket: [INF-966](https://2u-internal.atlassian.net/browse/INF-966)
=> fix: fixed notification type icons

src/Notifications/NotificationSections.jsx, src/Notifications/data/redux.test.js, src/Notifications/data/selectors.js, src/Notifications/data/slice.js, src/Notifications/data/thunks.js, src/Notifications/notificationSections.test.jsx
Fixed loading spinner was not visible when notifications are loading in notifications list.
Ticket: [INF-964](https://2u-internal.atlassian.net/browse/INF-964)
=> fix: added spinner when notifications are loading

package-lock.json, package.json
**Dependencies Revert PR for [425]( https://github.com/edx/frontend-component-header-edx/pull/425)**
- These Dependencies re-arrangement might be the reason for breaking the learning MFE because of multiple packages of same library. For libraries like frontend-platform, this means two versions of frontend-platform will be running at once and the MFE will fail to load.
**Possible issue**
Our headers and other libraries are not bundled before being published, meaning that they are not supposed to actually depend - at build time - on libraries like frontend-platform, etc. By moving these dev dependencies into dependencies, the consuming MFE will install versions of those deps into node_modules/@edx/frontend-component-header/node_modules... and that code will then use those versions instead …
=> fix: removed devDependencies from dependencies

src/Notifications/NotificationSections.jsx, src/Notifications/index.jsx, src/index.scss
[INF-1001](https://2u-internal.atlassian.net/browse/INF-1001)
Notification tray sticks to the top when the entire page is scrolled down.
**Screenshot**
=> feat: Notifications tray should stick to the top

src/Notifications/tours/constants.js, src/Notifications/tours/messages.js
[INF-1023](https://2u-internal.atlassian.net/browse/INF-1023)
1. Update the tour text 
2. Add learner's guide link
=> fix: update notification tour text and documentation link

src/index.scss
[INF-1051](https://2u-internal.atlassian.net/browse/INF-1051)
Currently the focus state contrast is not high enough for accessibility standards (see picture). Use Primary/500 (#00262B)
Now focus state is using Primary/500 (#00262B) color.
**Screenshot**
=> fix: fixed focus state bell color

src/Header.jsx, src/Header.messages.jsx, src/Header.test.jsx, src/learning-header/AuthenticatedUserDropdown.jsx, src/learning-header/messages.js
[REV-3693](https://2u-internal.atlassian.net/browse/REV-3693).
Modifying the menu item back to `Order History` instead of `Orders & Subscriptions`.
This PR manually reverts changes done in https://github.com/edx/frontend-component-header-edx/pull/390
=> feat: Update Orders & Subscriptions menu item back to Order History

src/Notifications/index.jsx, src/index.scss
[INF-1052](https://2u-internal.atlassian.net/browse/INF-1052)
Fixed following issues.
1. The notifications tray looks to be overlapping the NAV
2. When I scroll down the page I see a gap at the top, showing other LMS content:
3. There’s also a gap on the right, showing LMS content:
=> fix: notification tray height issues

src/Notifications/NotificationEmptySection.jsx, src/Notifications/NotificationSections.jsx, src/Notifications/NotificationTabs.jsx, src/Notifications/context.js, src/Notifications/index.jsx, src/Notifications/messages.js, src/Notifications/notificationSections.test.jsx, src/Notifications/notificationTabs.test.jsx, src/index.scss
[INF-1082](https://2u-internal.atlassian.net/browse/INF-1082)
1. "No notification yet" message should be visible in the notification tray when there is no notification for the user.
Figma: [Notifications](https://www.figma.com/file/1WsIDaf9Alfy2r8eNYj6vX/Notifications?type=design&node-id=678-15078&mode=design)
2. Added test case "Successfully showed No notification yet message when the notification tray is empty".
**Before**
**After**
=> feat: added no notifition yet message bar

src/Notifications/notification.scss
[INF-1152](https://2u-internal.atlassian.net/browse/INF-1152)
Alignment of notification badge is out on safari browser.
**Before**
**After**
=> fix: fixed issue of badge aligment on safari

src/studio-header/utils.js
JIRA Ticket: [TNL-11179](https://2u-internal.atlassian.net/browse/TNL-11179)
> When we try to click on 'Studio Home' under username, we repeatedly encounter the error message stating that 'Studio Home' cannot be reached.
Testing
On each of the Cours Authoring pages, check that the "Studio Home" option in the user menu properly navigates the user back to the home page.
=> fix: broken studio home link

src/Notifications/NotificationEmptySection.jsx
[INF-1163](https://2u-internal.atlassian.net/browse/INF-1163)
---
Fixed bell icon alignment for notification empty section.
---
**Before**
----
**After**
=> fix: fixed bell icon alignment for empty section

src/Notifications/NotificationEmptySection.jsx, src/Notifications/index.jsx, src/Notifications/tours/constants.js, src/Notifications/tours/data/hooks.js, src/Notifications/tours/messages.js
[INF-1172](https://2u-internal.atlassian.net/browse/INF-1172)
Description
We have 1 product tour currently active:
- Notifications tray
These features are not “new” especially to ~2000 users signing up daily. They have 3 more clicks to do before they can interact with discussions and the product tours may be somewhat distracting to a user. We need to deactivate all product tours that we created.
=> feat: removed sort and filter tour

example/index.js, src/DesktopHeader.jsx, src/Header.jsx, src/Header.test.jsx, src/learning-header/AuthenticatedUserDropdown.jsx, src/learning-header/LearningHeader.jsx, src/learning-header/LearningHeader.test.jsx, src/studio-header/HeaderBody.jsx, src/studio-header/StudioHeader.jsx, src/studio-header/StudioHeader.test.jsx, src/studio-header/UserMenu.jsx
In the spirit of making registration experience quick and easy (more details on [MVP scope doc](https://2u-internal.atlassian.net/wiki/spaces/Ecomm/pages/653164545/Registration+Login+Progressive+Profiling+Profile+Account+Management+MVP#MVP-Scope-Estimate)), we want to be able to remove username from the registration form. This creates the need to remove it everywhere on the UX too. As part of this initiative, we will be removing username from the headers and making the dropdown consistent with [edx.org](http://edx.org/) site.
**Changes**
Set the flag `HIDE_USERNAME_FROM_HEADER` to hide the username from the header and replace the username with the name for the screen reader text when the flag is enabled.
The flag will be removed when this …
=> feat: remove username from header

src/DesktopHeader.jsx, src/Header.jsx, src/Header.test.jsx, src/MobileHeader.jsx, src/Notifications/data/selectors.js, src/Notifications/index.jsx, src/__snapshots__/Header.test.jsx.snap, src/data/selectors.js
[INF-1508](https://2u-internal.atlassian.net/browse/INF-1508)
We are integrating the notification tray into the common header for both desktop and mobile versions. This will allow all MFEs using this common header to include the notification icon in their headers.
=> feat: added notification tray for common header/learner dashboard

src/learning-header/AuthenticatedUser.jsx, src/new-notifications/data/hook.js
[INF-1603](https://2u-internal.atlassian.net/browse/INF-1603)
Description Resolved the issue with Count API being recalled on each tab switch.
=> fix: fixed count api recalling issue

src/Notification/data/hook.js, src/Notification/index.jsx, src/Notification/index.test.jsx
Added support to open notification tray from query params
- `showNotifications` query param can be used to open notification tray
- `app` query can be used to open specific tab
Ticket Link: [INF-1677](https://2u-internal.atlassian.net/browse/INF-1677)
=> feat: added support to open notification tray from query params

src/Notification/index.jsx
Description
Updated the notifications preferences URL in the notification tray.
Old URL: https://account.edx.org/notifications
New URL: https://account.edx.org/#notifications
=> fix: updated notifications preferences url

example/index.scss, package-lock.json, package.json, src/Menu/menu.scss, src/index.scss, src/studio-header/StudioHeader.scss
- Upgrades peer dependency on `@openedx/paragon` to `^23.0.0` (**BREAKING CHANGE**)
- Changes `@edx/brand` npm alias to refer to `@edx/elm-theme` in dev dependencies.
- Example app `index.scss` file has been updated to pull from the new location of the CSS files for `openedx/paragon` and `edx/elm-theme`
- Pull down this branch
- Make sure you are logged in on your local instance
- Run `npm ci` and `npm start`
- Go to localhost:8080
- To confirm that design tokens are being used, you can inspect the CSS for any component and look for CSS variables
- Another giveaway that elm-theme is being used correctly would be to look at the button component for "Sign Up" -- it should have completely rounded edges as shown in the screenshot
New header:
Old header:
=> feat!: upgrade to @openedx/paragon v23 and design tokens
